[package]
name = "common"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[lints]
workspace = true

[dependencies]
log    = { version = "0.4", default-features = false, features = [] }
rustix = { version = "1.1", default-features = false, features = [
  "std",
  "alloc",
  "fs",
  "net",
  "mm",
  "shm",
  "param",
  "process",
  "thread",
  "time",
] }
# the only reason we are using this is that it lets us use Path and PathBuf
# without Rust's std
typed-path = { version = "0.12", default-features = false, features = [ "std" ] }

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
fastrand = { version = "2.3", default-features = false, features = [ "std" ] }
